image: Visual Studio 2015
configuration: Release
platform: x64
clone_depth: 1

environment:

  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: -t7z -m0=lzma -mx=9
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

  PGUSER: postgres
  PGPASSWORD: Password12!

  matrix:

  - pg: none # pg is installed on MSYS2 and the (pg 15.1 Jun 2023) binaries are used
    PlatformToolset: v143
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    rversion: 4.3.1
    compiler: msys2

  - pg: 15.3-2
    PlatformToolset: v143
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    rversion: 4.2.3
    compiler: msvc

  - pg: REL_16_BETA1 # static commit from git
    PlatformToolset: v143
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    rversion: 4.3.1
    compiler: msys2

#
#   - pg: master
#     PlatformToolset: v141
#     configuration: Debug
#     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
#     rversion: 4.2.3
#     compiler: msvc
#
#   - pg: REL_16_BETA1
#     PlatformToolset: v143
#     configuration: Debug
#     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
#     rversion: 4.2.3
#     compiler: msvc
#
#   - pg: REL_15_3
#     PlatformToolset: v143
#     configuration: Debug
#     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
#     rversion: 4.2.3
#     compiler: msvc
#
#   - pg: 15.3-2
#     PlatformToolset: v143
#     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
#     rversion: 4.2.3
#     compiler: msvc
#
#   - pg: 15.3-2
#     PlatformToolset: v143
#     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
#     rversion: 4.1.3
#     compiler: msvc
#
#   - pg: 14.8-2
#     PlatformToolset: v143
#     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
#     rversion: 4.2.3
#     compiler: msvc
#
#   - pg: 14.8-2
#     PlatformToolset: v143
#     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
#     rversion: 4.1.3
#     compiler: msvc
#
#   - pg: 13.11-2
#     PlatformToolset: v143
#     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
#     rversion: 4.2.3
#     compiler: msvc
#
#   - pg: 13.11-2
#     PlatformToolset: v143
#     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
#     rversion: 4.1.3
#     compiler: msvc
#
#   - pg: 12.15-2
#     PlatformToolset: v143
#     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
#     rversion: 4.2.3
#     compiler: msvc
#
#   - pg: 12.15-2
#     PlatformToolset: v143
#     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
#     rversion: 4.1.3
#     compiler: msvc
#
#   - pg: 11.20-2
#     PlatformToolset: v140
#     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#     rversion: 4.2.3
#     compiler: msvc
#
#   - pg: 11.20-2
#     PlatformToolset: v140
#     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#     rversion: 4.1.3
#     compiler: msvc
#
#   - pg: 10.23-1
#     PlatformToolset: v120
#     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#     rversion: 4.2.3
#     compiler: msvc
#
#   - pg: 10.23-1
#     PlatformToolset: v120
#     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#     rversion: 4.1.3
#     compiler: msvc

matrix:
  allow_failures:
    - pg: master

for:
-
  matrix:
    only:
      - compiler: msys2

  init:
  - echo compiler msys2 init
  - systeminfo
  # https://stackoverflow.com/questions/5089389/how-can-i-check-what-version-edition-of-visual-studio-is-installed-programmatica
  - if not "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property productId
  - if not "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property catalog_productLineVersion
  # Make %x64% available for caching
  # a variable used in the Appveyor cach area must be defined in the init
  - set gitrevshort=%APPVEYOR_REPO_COMMIT:~0,8%
  - ps: |
      # Set-PSDebug -Trace 2

      if ("${env:Platform}" -eq "x64") {
        ${env:MSYSTEM} = "MINGW64"
        ${env:OSBitVersion} = "x86_64"
      } else {
        ${env:MSYSTEM} = "MINGW32"
        ${env:OSBitVersion} = "i686"
      }

      if ("${env:MSYSTEM}" -eq "MINGW64") {
        ${env:R_ARCH} = "/x64"
      } else {
        ${env:R_ARCH} = "/i386"
      }

      ${env:rbinurl} = "https://cran.r-project.org/bin/windows/base/old/${env:rversion}/R-${env:rversion}-win.exe"
      # "make installcheck" does not like spaces
      ${env:R_HOME} = "C:\RINSTALL"

      if ("${env:Platform}" -eq "x64") {
        ${env:bit} = "64"
      } else {
        ${env:bit} = "32"
      }
      ${env:betterperl} = "strawberry${env:bit}"
      ${env:betterperlurl} = "https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-${env:bit}bit-portable.zip"

  # Nix does not like spaces
  - ps: ${env:R_HOME} = "C:\RINSTALL"

  #
  # possible user provided in the matrix
  #

  - if not defined pghint          set pghint=none
  - if not defined pg              set pg=none
  - if not defined pglinkbinoldurl set pglinkbinoldurl=none
  - if not defined rversionurl set rversionurl=https://cran.r-project.org/bin/windows/base/old/%rversion%/R-%rversion%-win.exe

  - ps: ${env:PATH} = "C:\msys${env:bit}\${env:MSYSTEM}\bin;C:\msys${env:bit}\usr\bin;${env:PATH}"
  - echo PATH
  - echo %PATH%

  install:
  - if not exist R-%rversion%-win.exe appveyor downloadfile https://cran.r-project.org/bin/windows/base/old/%rversion%/R-%rversion%-win.exe

  - R-%rversion%-win.exe /VERYSILENT /DIR=%R_HOME% /NOICONS /TASKS=

  # From the version
  - ps: |
      if("${env:pg}" -ne "none") {
        ${env:pgorig}    = "none"
        ${env:pgversion} = ${env:pg}
      }
      # if pg equals "none" that is the  "msys2" binary case,
      # then later in the .sh scripts, "pgversion" will be determined by SQL

  #
  # only used about a custom PostgreSQL build (not an MSYS2 already compiled binary)
  #
  # Nix does not like spaces
  - ps: ${env:pgroot} = "C:\PGINSTALL"
  - mkdir "%pgroot%"

  - ps: |
      # Set-PSDebug -Trace 2
      if (-not (Test-Path "${env:betterperl}.zip")) {
        dir
        curl -o "${env:betterperl}.zip" -v "${env:betterperlurl}"
        dir
      }
      7z x    "${env:betterperl}.zip" "-oc:\${env:betterperl}"
      #
      # Later, strawberry perl is put in front of the PATH
      # in the called file build_script.sh.
      #
      # Environment variables (except PATH that is replaced)
      # are readable in the called bash scripts.

  #
  # PostgreSQL from source code: git, tag, or commit
  #
  - ps: |
      # Set-PSDebug -Trace 2
      if ("${env:pg}" -ne "none") {
        git config --global advice.detachedHead false
        # VS Code 2015 works fine
        $env:PATH += ";C:\msys${env:bit}\usr\bin;C:\msys${env:bit}\mingw${env:bit}\bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64"
        #
        # git branch or commit - alphanumeric and all lowercase letters (slower download)
        #
        if("${env:pghint}" -eq "commit") {
          git clone -q                            https://git.postgresql.org/git/postgresql.git c:\projects\postgresql
          pwd
          pushd c:\projects\postgresql
          pwd
          git checkout -q                 ${env:pg} -b ${env:pg}
          git branch
          echo ${env:pg}
          popd
          pwd
        #
        # git branch or tag(detached head)
        # PostgreSQL case - git branches and tags have at least one capital letter - but expect mostly CAPS
        #
        } else {
          git clone -q --depth 1 --branch ${env:pg} https://git.postgresql.org/git/postgresql.git c:\projects\postgresql
          pushd c:\projects\postgresql
          pwd
          git branch
          echo ${env:pg}
          popd
          pwd
        }
        pushd c:\projects\postgresql
        dir
        popd
      }

  # msys2
  #
  # update all - skip - postgres and R are weakly and near nothing dependent on versions
  # - bash --login -c "set -e;set -x;set -v;pacman -Suy --noconfirm"
  # - bash --login -c "set -e;set -x;set -v;pacman -Suy --noconfirm"
  #
  # just in case I need this for some pg builds
  # - bash --login -c "pacman --noconfirm -S --needed mingw-w64-${OSBitVersion}-icu"
  # just in case I need icu debug libraries
  # - bash --login -c "pacman --noconfirm -S --needed mingw-w64-${OSBitVersion}-icu-debug-libs"
  # just in case I need icu development
  # - bash --login -c "pacman --noconfirm -S --needed icu-devel"
  # icu info
  # - bash --login -c "icu-config --ldflags"
  #
  # Nov Dec 2021 Appveyor changed the PATH
  # The [first] winpty.exe found is [the] "wrong [one]"
  #
  # Attempt to avoid the error:
  #
  # 1 [main] winpty (2980) C:\Program Files\Git\usr\bin\winpty.exe: *** fatal error - cygheap base mismatch detected
  # This problem is probably due to using incompatible versions of the cygwin DLL
  #
  - bash --login -c "pacman --noconfirm -S --needed winpty"

  # PostgreSQL from an MSYS2 already-compiled-binary.
  - if "%pg%"=="none" (
      bash --login -c "pacman --noconfirm -S --needed ${MINGW_PACKAGE_PREFIX}-postgresql"
    )

  #
  # How to obtain older versions of packages using MSYS2?
  # 2015
  # https://stackoverflow.com/questions/33969803/how-to-obtain-older-versions-of-packages-using-msys2
  #
  - if "%pg%"=="none" if not "%pglinkbinoldurl%"=="none" (
      bash -login -c "curl   -o             install.pkg.tar.zst ${pglinkbinoldurl}" &
      bash -login -c "pacman -U --noconfirm install.pkg.tar.zst"
    )

  build_script:

  - echo set
  - set
  - bash --login -c "$(cygpath ${APPVEYOR_BUILD_FOLDER})/build_script.sh"

  test_script:
  - bash --login -c "$(cygpath ${APPVEYOR_BUILD_FOLDER})/test_script.sh"
  
  after_test:
  - bash --login -c "$(cygpath ${APPVEYOR_BUILD_FOLDER})/after_test.sh"


-
  matrix:
    only:
      - compiler: msvc

  init:
  - echo compiler msvc init
  - systeminfo
  # https://stackoverflow.com/questions/5089389/how-can-i-check-what-version-edition-of-visual-studio-is-installed-programmatica
  - if not "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property productId
  - if not "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property catalog_productLineVersion
  # Make %x64% available for caching
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  # a variable used in the Appveyor cache area must be defined in the init
  - ps: |
      if ("$env:Platform" -eq "x64") {
        $env:pf = "$env:ProgramFiles"
        $env:x64 = "-x64"
      } else {
        $env:pf = "${env:ProgramFiles(x86)}"
      }
      $env:exe = "postgresql-$env:pg-windows$env:x64.exe"
      [Environment]::SetEnvironmentVariable("exe", $env:exe, "Machine")

      if ("${env:Platform}" -eq "x64") {
        ${env:bit} = "64"
      } else {
        ${env:bit} = "32"
      }
      ${env:betterperl} = "strawberry${env:bit}"
      ${env:betterperlurl} = "https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-${env:bit}bit-portable.zip"

  - set exe=postgresql-%pg%-windows%x64%.exe
  - setx /m exe %exe%

  install:
  - if not exist R-%rversion%-win.exe appveyor downloadfile https://cran.r-project.org/bin/windows/base/old/%rversion%/R-%rversion%-win.exe
  - R-%rversion%-win.exe /VERYSILENT

  #
  # From the EnterpriseDB version name,
  # if any, strip off the: right-most part dot, then numbers, then one hyphen, then numbers.
  - ps: $env:pgversion = $env:pg -replace "[.]\d+-\d+$", ""
  #
  - echo pgversion=%pgversion%
  - set pgroot=%pf%\PostgreSQL\%pgversion%
  - echo %pgroot%
  - SET R_HOME=%ProgramFiles%\R\R-%rversion%
  - set RBIN=%PLATFORM:x86=i386%
  - SET sed=C:\msys64\usr\bin\sed

  # Appveyor specific: seems not required - with Appveyor - Strawberry perl is already in the path
  # ActiveState Perl is good, but Strawberry Perl is preferred
  #
  - ps: |
      # Set-PSDebug -Trace 2
      if (-not (Test-Path "${env:betterperl}.zip")) {
        curl -o "${env:betterperl}.zip" -v "${env:betterperlurl}"
      }
      7z x    "${env:betterperl}.zip" "-oc:\${env:betterperl}"
      # of needed to install pl/perl
      ${env:PATH} = "c:\${env:betterperl}\perl\bin;${env:PATH}"
      which perl
      ${env:PATH} = "${env:PATH};c:\${env:betterperl}\c\bin"
      which pexports


  # R in the path is not required: msvc compilation
  # R in the path is required: find Rscript
  - set PATH=%R_HOME%\bin\%rbin%;%PATH%
  # environment variable "postgresrcroot" is required for msvc.diff.R
  - set postgresrcroot=C:\projects\postgresql

  - ps: |
      # "branchtagcommit" exists only because, this makes an easier test in a windows batch
      # This environment variable is use in a test that is used that is used in determining
      # whether or not to perform patching (see below).
      #
      if ("${env:pg}" -notmatch "[.]") {
        ${env:branchtagcommit} = "yes"
      } else {
        ${env:branchtagcommit} = "no"
      }
      echo "branchtagcommit ${env:branchtagcommit}"

  - ps: |
      # notmatch - if no "dot is found" in pg name, then pg is a: git: branch, tag, or commit.
      if ("${env:branchtagcommit}" -eq "yes") {
        $env:Path += ";C:\msys64\usr\bin;C:\msys64\mingw64\bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64"
        git config --global advice.detachedHead false
        #
        # git commit
        #
        if(("${env:pg}" -cmatch  "^[a-z0-9]+$") -and ("${env:pghint}" -eq "commit")) {
          git clone -q  https://git.postgresql.org/git/postgresql.git  c:\projects\postgresql
          pushd c:\projects\postgresql
          git checkout -q  ${env:pg} -b ${env:pg}
          popd
        #
        # git branch or tag(detached head)
        # PostgreSQL case - git branches and tags have at least one capital letter - but expect mostly CAPS
        #
        } else {
          git clone -q --depth 1 --branch ${env:pg} https://git.postgresql.org/git/postgresql.git  c:\projects\postgresql
        }
        gendef - "$env:R_HOME\bin\$env:rbin\R.dll" > "R$env:PLATFORM.def" 2> $null
        lib "/def:R$env:PLATFORM.def" "/out:R$env:PLATFORM.lib" "/MACHINE:$env:PLATFORM"
        pushd c:\projects\postgresql
        pwd
        cmd /c mklink /J contrib\plr $env:APPVEYOR_BUILD_FOLDER
        Rscript --vanilla "${env:APPVEYOR_BUILD_FOLDER}\msvc.diff.R"
        perl contrib\plr\buildsetup.pl
        echo  "AFTER perl contrib\plr\buildsetup.pl CONTENTS OF C:\projects\postgresql\pgsql.sln"
        type  C:\projects\postgresql\pgsql.sln
        popd
        pwd
        $env:PROJ="C:\projects\postgresql\pgsql.sln"
        $env:dll="c:\projects\postgresql\$env:CONFIGURATION\plr\plr.dll"
      } else {
        $env:PROJ="plr.vcxproj"
        $env:dll="$($env:PLATFORM.replace('x86', '.'))\$env:CONFIGURATION\plr.dll"
        if (-not (Test-Path "$env:pgroot\bin")) {
          if (-not (Test-Path "$env:exe")) {
            Start-FileDownload "http://get.enterprisedb.com/postgresql/$env:exe"
          }
          & ".\$env:exe" --unattendedmodeui none --mode unattended --superpassword "$env:PGPASSWORD" --servicepassword "$env:PGPASSWORD" | Out-Null
          Stop-Service "postgresql$env:x64-$env:pgversion"
        }
      }

  #
  # Only when compiling pg from scratch.
  # If pg is not being compiled then pgsql.sln will not exist and not have been created.
  #
  # The semi-duplicate extra 'plr' entry in the pgsql.sln file
  # prevents building if Microsoft Visual Studio is the version 2019 and greater.
  #
  - if exist C:\projects\postgresql\pgsql.sln if "%branchtagcommit%"=="yes" (
      echo REMOVE plr ENTRY from pgsql.sln &
      echo FILE BEFORE clean_pgsql_sln.sh C:\projects\postgresql\pgsql.sln &
      type      C:\projects\postgresql\pgsql.sln &
      bash -lc '/c/projects/plr/clean_pgsql_sln.sh' &
      echo FILE AFTER clean_pgsql_sln.sh C:\projects\postgresql\pgsql.sln &
      type      C:\projects\postgresql\pgsql.sln
    )

  build_script:
  - msbuild /p:PlatformToolset=%PlatformToolset% /p:configuration=%CONFIGURATION% /p:platform=%PLATFORM%
            %PROJ%
            /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

  after_build:
  - appveyor AddMessage Packing -Category Information
  - md tmp\share\extension
  - copy *.sql tmp\share\extension\
  - copy *.control tmp\share\extension\
  - copy LICENSE tmp\PLR_LICENSE
  - md tmp\lib
  - md tmp\symbols
  - copy %dll% tmp\lib
  - copy %dll:.dll=.pdb% tmp\symbols
  - set zip=plr-%APPVEYOR_REPO_COMMIT:~0,8%-pg%pgversion%-R%rversion%-%PLATFORM%-%CONFIGURATION%.7z
  - 7z a -t7z -mmt24 -mx7 -r %zip% .\tmp\* > nul
  - ps: |
      if ("$env:pg" -notmatch "[.]") {
        pushd c:\projects\postgresql\src\tools\msvc
        perl install.pl "$env:pgroot"
        popd
      }

  test_script:
  - path %pgroot%\bin;%PATH%
  - ps: |
      if ("${env:branchtagcommit}" -eq "yes") {
        Set-Content -path pg.pass -value "$env:pgpassword" -encoding ascii
        initdb -A md5 -U "$env:PGUSER" --pwfile=pg.pass C:\pgdata
        pg_ctl register -S demand -N "postgresql$env:x64-$env:pgversion" -D c:\pgdata
      } else {
        Add-AppveyorMessage "Copying the extension files to the PostgreSQL directories." -Category Information
        7z x "$env:zip" "-o$env:pgroot"
      }
  - appveyor AddMessage "Starting the database server." -Category Information
  - setx /M PATH "%R_HOME%\bin\%rbin%;%PATH%"
  - net start postgresql%x64%-%pgversion%

  - ps: |
      Add-AppveyorTest Regression -Framework pg_regress -FileName sql\ -Outcome Running
      if (("9.3", "9.4").Contains("$env:pgversion")) {
        $env:psqlopt="--psqldir"
      } else {
        $env:psqlopt="--bindir"
      }
      $env:Outcome="Passed"
      $elapsed=(Measure-Command {
        pg_regress "$env:psqlopt=$env:pgroot\bin" --dbname=pl_regression plr `
          bad_fun opt_window do out_args plr_transaction opt_window_frame 2>&1 |
          %{ if ($_ -is [System.Management.Automation.ErrorRecord]) { $_.Exception.Message } else { $_ } } |
            Out-Default
        if ($LASTEXITCODE -ne 0) {
          $env:Outcome="Failed"
        }
      }).TotalMilliseconds
      Update-AppVeyorTest Regression -Framework pg_regress -FileName sql\ -Outcome "$env:Outcome" -Duration $elapsed
      if ("$env:Outcome" -ne "Passed") {
        type regression.diffs
        $host.SetShouldExit($LastExitCode)
      }

#on_failure:
# - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

cache:
- '%exe%'
- R-%rversion%-win.exe
- '%betterperl%.zip'
- 'pg-pg%pgversion%-%Platform%-%Configuration%-%compiler%.7z'

artifacts:
- path: 'plr*.7z'

deploy:
   provider: GitHub
   release: $(appveyor_repo_tag_name)
   draft: false
   prerelease: false
   auth_token:
      secure: sFXG3dBiC2S9bnHbDfg2fS0OdaxiSr6fGSlMQvQPb0lJGyKM3E5UZum4rik60zyi
   on:
      appveyor_repo_tag: true

