
version: 1.0.{build}.{branch}
clone_depth: 1

environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
  R_VERSION: 4.0.5

  matrix:
    - MSYSTEM: MINGW64
    # - MSYSTEM: MINGW32

init:
- ps: |
    Set-PSDebug -Trace 2
    ${env:PATH} = "C:\msys64\${env:MSYSTEM}\bin;C:\msys64\usr\bin;C:\msys64\bin;${env:PATH}"

    if ("${env:MSYSTEM}" -eq "MSYSTEM") {
      ${env:R_ARCH} = "/x64"
      ${env:COMPONENTS_ARCH} = "',x64'"
    } else {
      ${env:R_ARCH} = "/i386"
      ${env:COMPONENTS_ARCH} = "',i386'"
    }

    ${env:RBINURL} = "https://cran.r-project.org/bin/windows/base/old/${env:R_VERSION}/R-${env:R_VERSION}-win.exe"
    # "make installcheck" does not like spaces
    ${env:R_HOME} = "C:\RINSTALL"

    # also see that each *.sh dot sources early ". ./init.sh"

install:
- ps: |
    Set-PSDebug -Trace 2
    if (-not (Test-Path "R-${env:R_VERSION}-win.exe")) {
      curl -o "R-win.exe" -v "${env:RBINURL}"
      dir "R-win.exe"
      Invoke-Command -ScriptBlock {C:\projects\plr\R-win.exe /SP- /VERYSILENT /DIR=C:\RINSTALL /NOICONS /TASKS=}
      dir "C:\RINSTALL"
    }
    bash --login -c "pacman --noconfirm -S --needed ${MINGW_PACKAGE_PREFIX}-postgresql"

build_script:
- ps: |
    Set-PSDebug -Trace 2
    bash --login -c "$(cygpath ${APPVEYOR_BUILD_FOLDER})/build_script.sh"

test_script:
- ps: |
    Set-PSDebug -Trace 2
    bash --login -c "$(cygpath ${APPVEYOR_BUILD_FOLDER})/test_script.sh"

