name: plr CI 
run-name: plr CI - ${{ github.event.head_commit.message }}

on: 
   push:
   pull_request: 
   workflow_dispatch:

jobs:
  msys2-clangarm64:
    runs-on: windows-11-arm
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: CLANGARM64
          update: true
      - name: CI-Build
        shell: msys2 {0}
        run: |
          set -x -v -e
          echo Hello
