
name: Callee of plr Ubuntu jobs
run-name: Callee of plr Ubuntu jobs - ${{ github.event.head_commit.message }}

env:
  TZ: UTC

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        required: false
        default: false

  workflow_call:
    inputs:
      debug_enabled:
        type: boolean
        required: false
        default: false
#     PG:
#       required: true
#       default: '18'
#       type: string
#     R:
#       required: true
#       default: 'repo'
#       type: string
#     os:
#       required: true
#       default: 'ubuntu-latest'
#       type: string
      ragged_schedule:
        type: string
        required: true

jobs:

  ubuntu_job_runner:
    name: PG ${{ matrix.pg }} R ${{ matrix.R }} os ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    # Unexpected value 'false'
    continue-on-error: ${{ matrix.GithubActionsIgnoreFail == 'true' && true || false }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(inputs.ragged_schedule) }}

    steps:

    - name: Git Checkout this Repository Code
      uses: actions/checkout@v6
      
    - name: Get Linux Host Information
      run: |
        bash ./get_linux_host_info.sh

    - name: Guarantee PostgreSQL is Not Installed
      run: |
        bash ./guarantee_postgres_is_not_installed.sh

    - name: Refresh APT
      run: |
        set -x -v -e
        sudo apt-get update -qq

    - name: Acquire PostgreSQL-Dev (and PostgreSQL to test)
      run: |
        set -x -v -e
        # two(2) consecutive digits
        if [ $(echo "${{ matrix.PG }}" | grep -qE "^[0-9][0-9]$" && echo 0) ]
        then
          echo "Postgres from repository binary ..."
          bash ./get_postgres_binaries_compiled_on_ubuntu_from_postgres.org.sh ${{ matrix.PG }}
        else
          echo "Postgres from source ..."
          bash ./get_latest_postgres_source_branch_or_tag.sh ${{ matrix.PG }}
        fi

    - name: Acquire R-Dev (and R to test)
      run: |
        set -x -v -e
        echo "R from CRAN ..."
        bash ./get_debian_r_binaries_on_ubuntu_from_cran.sh

    - name: Install PL/R
      run: |
        set -x -v -e
        # two(2) consecutive digits
        if [ $(echo "${{ matrix.PG }}" | grep -qE "^[0-9][0-9]$" && echo 0) ]
        then
          echo "PL/R from Postgres from repository binary ..."
          bash ./build_install_plr_from_binary_postgres_on_ubuntu.sh
        else
          echo "PL/R from Postgres from source ..."
          bash ./build_install_plr_and_postgres_from_source_on_ubuntu.sh
        fi

    - name: Debug with SSH owenthereal/action-upterm@v1
      uses: owenthereal/action-upterm@v1
      with:
        wait-timeout-minutes: 5
        limit-access-to-actor: true

    - name: Test (Check) PL/R
      run: |
        set -x -v -e
        # two(2) consecutive digits
        if [ $(echo "${{ matrix.PG }}" | grep -qE "^[0-9][0-9]$" && echo 0) ]
        then
          echo "Test of PL/R from Postgres from repository binary ..."
          bash ./test_plr_from_binary_postgres_on_ubuntu.sh
        else
          echo "Test of PL/R from Postgres from source ..."
          bash ./test_plr_from_source_postgres_on_ubuntu.sh
        fi
