name: plr CI 
run-name: plr CI - ${{ github.event.head_commit.message }}

on: 
   push:
   pull_request: 
   workflow_dispatch:

jobs:

  job_master:
    name: PG master ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - name: Echo site details
        run: echo building - master
 
      - name: Checkout code
        uses: actions/checkout@v6
 
      - name: checkout postgres
        run: |
          sudo apt-get update -qq
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
          sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"
          sudo apt-get install -qq r-base-dev acl bison flex libssl-dev
          sudo R --version
          sudo /etc/init.d/postgresql stop
          sudo apt-get remove --purge postgresql\*
          sudo rm -rf /etc/postgresql /var/lib/postgresql
          git clone https://github.com/postgres/postgres.git
          pushd postgres
          git checkout master
          ./configure
          make -j4
          sudo make install
          export PATH=/usr/local/pgsql/bin:$PATH
          initdb -D data
          pg_ctl -D data -l logfile start
          psql -d postgres -c "SELECT version();"
          psql -d postgres -c "SELECT current_setting('server_version_num');"
          popd

      - name: Script
        run: |
          export USE_PGXS=1
          export PATH=/usr/local/pgsql/bin:$PATH
          SHLIB_LINK=-lgcov PG_CPPFLAGS="-fprofile-arcs -ftest-coverage -O0" make
          # USE_PGXS=1 is not required in Travis, and it is required in Github Actions
          sudo USE_PGXS=1 PATH=/usr/local/pgsql/bin:$PATH make install
          make installcheck || (cat regression.diffs && false)
        env:
          USE_PGXS: 1

  job_REL_19_ubuntu-latest:
    name: PG REL_19_ ubuntu-latest
    # SEEN JUN 2026
    # Ubuntu 24.04 - ubuntu-latest or ubuntu-24.04
    # https://github.com/actions/runner-images
    # noble (24.04, LTS), plucky (25.04, amd64 only)
    # https://wiki.postgresql.org/wiki/Apt
    # https://apt.postgresql.org/pub/repos/apt/dists/
    # ##
    # https://ftp.postgresql.org/pub/repos/apt/dists/noble-pgdg/
    # Regular expression search - "Package: postgresql-18$"
    # https://ftp.postgresql.org/pub/repos/apt/dists/noble-pgdg/main/binary-amd64/Packages
    runs-on: ubuntu-latest
    steps:
      - name: Echo site details
        run: echo building master
 
      - name: Checkout code
        uses: actions/checkout@v6
 
      - name: checkout postgres
        run: |
          set -x -v -e
          sudo apt-get update -qq
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
          sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"
          sudo apt-get install -qq r-base-dev acl bison flex libssl-dev
          sudo R --version
          sudo /etc/init.d/postgresql stop
          sudo apt-get remove --purge postgresql\*
          sudo rm -rf /etc/postgresql /var/lib/postgresql
          export PGSRCVERSION=REL_19_
          export ALLGITTAGS=$(git ls-remote --tags https://github.com/postgres/postgres.git | cut -c 52-)
          quantity() { echo ${ALLGITTAGS} | tr " " "\n" | grep -c "${PGSRCVERSION}${MARK}[0-9]"; }
          quality()  { echo ${ALLGITTAGS} | tr " " "\n" | grep -e "${PGSRCVERSION}${MARK}[0-9]" | tail -n 1; }
          export MARK=""
          export RET=$(quantity)
          if [ "${RET}" -gt "0" ]
          then
            export SPECGITTAG=$(quality)
            echo -n "Release(s) are found.  Taking the last Release . . . SPECGITTAG: ${SPECGITTAG}"
          else
            export MARK="RC"
            export RET=$(quantity)
            echo "Release(s) are not found.  Trying Release Candidates."
            if [ "${RET}" -gt "0" ]
            then
              export SPECGITTAG=$(quality)
              echo -n "Release Candidate(s) are found.  Taking the last Release Candidate . . . SPECGITTAG: ${SPECGITTAG}"
            else
              export MARK="BETA"
              export RET=$(quantity)
              echo "Release Candidate(s) are not found. Trying Betas."
              if [ "${RET}" -gt "0" ]
              then
                export SPECGITTAG=$(quality)
                echo -n "Beta(s) are found. Taking the last Beta . . . SPECGITTAG: ${SPECGITTAG}"
              else
                echo "Beta(s) are not found."
              fi
            fi
          fi
          echo "SPECGITTAG: ${SPECGITTAG}"
          git clone --branch $SPECGITTAG --depth=1 https://github.com/postgres/postgres.git
          pushd postgres
          ./configure
          make
          sudo make install
          export PATH=/usr/local/pgsql/bin:$PATH
          initdb -D data
          pg_ctl -D data -l logfile start
          psql -d postgres -c "SELECT version();"
          psql -d postgres -c "SELECT current_setting('server_version_num');"
          popd

      - name: Script
        run: |
          set -x -v -e
          export USE_PGXS=1
          export PATH=/usr/local/pgsql/bin:$PATH
          SHLIB_LINK=-lgcov PG_CPPFLAGS="-fprofile-arcs -ftest-coverage -O0" make
          # USE_PGXS=1 is not required in Travis, and it is required in Github Actions
          sudo USE_PGXS=1 PATH=/usr/local/pgsql/bin:$PATH make install
          make installcheck || (cat regression.diffs && false)
        env:
          USE_PGXS: 1

  job_master_ubuntu-24_04-riscv:
    name: PG master ubuntu-24.04-riscv
    runs-on: ubuntu-24.04-riscv
    steps:
      - name: Echo site details
        run: echo building master
 
      - name: Checkout code
        uses: actions/checkout@v6
 
      - name: Checkout
        run: |
          set -x -v -e

          export DEBIAN_FRONTEND=noninteractive
          # To build PostgreSQL and its C client library (libpq) from source
          sudo apt-get install --qq build-essential libreadline-dev zlib1g-dev flex bison libssl-dev -y
          git clone --branch master --depth 1 https://github.com/postgres/postgres.git postgres-src
          pushd postgres-src
          git checkout master
          ./configure --help
          ./configure --without-icu --without-readline --without-zlib --disable-rpath --enable-depend
          make 
          sudo make install
          export PATH=/usr/local/pgsql/bin:$PATH
          # andre added
          export PATH=/usr/local/pgsql/lib:${PATH}
          export LD_LIBRARY_PATH=/usr/local/pgsql/lib:${LD_LIBRARY_PATH}
          #
          initdb -D data
          pg_ctl -D data -l logfile start
          psql -d postgres -c "SELECT version();"
          psql -d postgres -c "SELECT current_setting('server_version_num');"
          popd

          sudo apt-get install -qq --no-install-recommends build-essential ca-certificates curl gcc gfortran libblas-dev libbz2-dev libcairo2-dev libcurl4-openssl-dev libicu-dev libjpeg-dev liblapack-dev liblzma-dev libpcre2-dev libpng-dev libreadline-dev libssl-dev libtiff-dev libx11-dev libxml2-dev libxt-dev zlib1g-dev -y
          #
          # https://rstudio.github.io/r-manuals/r-admin/Obtaining-R.html
          sudo apt-get install -qq subversion -y
          # r-devel
          svn checkout https://svn.r-project.org/R/trunk/ r-src
          pushd r-src
          ./configure --help
          ./configure --enable-R-shlib --disable-java --disable-byte-compiled-packages --disable-rpath --without-ICU --without-recommended-packages
          make
          sudo make install
          popd
          export PATH=/usr/local/bin:$PATH
          R --version
          popd

      - name: Script
        run: |
          set -x -v -e
          export PATH=/usr/local/pgsql/bin:$PATH
          # andre added
          export PATH=/usr/local/pgsql/lib:${PATH}
          export LD_LIBRARY_PATH=/usr/local/pgsql/lib:${LD_LIBRARY_PATH}
          # andre added
          export PATH=/usr/local/bin:$PATH
          
          export USE_PGXS=1
          export PATH=/usr/local/pgsql/bin:$PATH
          SHLIB_LINK=-lgcov PG_CPPFLAGS="-fprofile-arcs -ftest-coverage -O0" make
          # USE_PGXS=1 is not required in Travis, and it is required in Github Actions
          sudo USE_PGXS=1 PATH=/usr/local/pgsql/bin:$PATH make install
          make installcheck || (cat regression.diffs && false)
        env:
          USE_PGXS: 1

      - name: After Success
        # success() returns true, when none of the previous steps have failed or been canceled.
        if: ${{ success() }}
        # Uploads code coverage to codecov.io
        run: bash <(curl -s https://codecov.io/bash)



# # Install RISE RISC-V Runners (Personal)
# # Where do you want to install RISE RISC-V Runners (Personal)?
# # Also includes public repositories (read-only). ..
# # 1. AndreMikulec (CHOSE THIS ONE) -> (*)all\selected repositories [Install]
# #   with these permissions:
# #     Read access to actions and metadata
# #     Read and write access to administration
# #       [Install]
# #       All set, AndreMikulec!
# #       The RISE RISC-V Runners personal app is correctly installed on AndreMikulec.
# #
# #       You can now trigger GitHub Actions jobs with the 
# #         ubuntu-24.04-riscv label and they will be picked up automatically.
# #
# # 2. postgres-plr (I did nothing)
# # https://github.com/apps/rise-risc-v-runners-personal/installations/select_target
# # https://github.com/riseproject-dev/riscv-runner-sample/blob/main/.github/workflows/hello.yml
# # https://github.com/apps/rise-risc-v-runners-personal
# # ubuntu-24.04-riscv
# # RISE RISC-V Runners
# # GitHub App
# # https://github.com/apps/rise-risc-v-runners
# #
# # start(ed) with a copy of "job_18_ubuntu-24_04-arm"
# #
# # NOT WORKING - A WORK IN PROGRESS
# #
# job_master_ubuntu-24_04-riscv:
#   name: PG master ubuntu-24.04-riscv
#   runs-on: ubuntu-24.04-riscv
#   steps:
#     - name: Checkout code
#       uses: actions/checkout@v6
#
#     - name: Before Script
#       run: |
#         set -x -v -e
#         echo "Minimal"
#         uname -m
#         uname -a
#         cat /proc/cpuinfo
#         cat /etc/os-release
#         set +x +v +e
#         sudo apt-get update -y
#         sudo apt-get upgrade -y
#         #
#         # echo Building plr with PostgreSQL $PG
#         # sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
#         # wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
#         #
#         dpkg -l | grep postgres
#         # see the exact dependency tree
#         apt-cache depends postgresql
#         # see everything that would be installed
#         sudo apt-get            install --simulate postgresql
#         #
#         sudo /etc/init.d/postgresql stop
#         sudo systemctl stop postgresql
#         sudo apt-get --purge    remove "postgresql*" -y
#         sudo apt-get --purge    remove libpq5 libpq-dev -y
#         sudo apt-get --dry-run  autoremove -y
#         sudo apt-get            autoremove --purge -y
#         sudo apt-get            autoclean -y
#         sudo apt-get            clean -y
#         #
#         sudo rm -rf /etc/postgresql/
#         sudo rm -rf /var/lib/postgresql/
#         sudo rm -rf /var/log/postgresql/
#         sudo rm -rf /etc/postgresql-common/
#         #
#         sudo userdel -r postgres
#         sudo groupdel postgres
#         #
#         # debconf unable to initialize frontend Dialog
#         export DEBIAN_FRONTEND=noninteractive
#         #
#         # To build PostgreSQL and its C client library (libpq) from source
#         sudo apt-get install build-essential libreadline-dev zlib1g-dev flex bison libssl-dev -y
#         # default PostgreSQL client development libraries on Ubuntu
#         #   to be able to make the client-side pg_config utility to be at /usr/bin/pg_config
#         # sudo apt-get install libpq-dev -y
#         # cluster management utilities
#         # sudo apt-get install postgresql-common -y
#         git clone --branch master --depth 1 https://github.com/postgres/postgres.git postgres-src
#         pushd postgres-src
#         git checkout master
#         ./configure --help
#         ./configure --without-icu --without-readline --without-zlib --disable-rpath --enable-depend
#         make -j4
#         sudo make install
#         #
#         sudo adduser postgres
#         sudo mkdir -p /usr/local/pgsql/data
#         sudo chown postgres /usr/local/pgsql/data
#         #
#         sudo su - postgres
#         #
#         export PATH=/usr/local/pgsql/bin:$PATH
#         export PATH=/usr/local/pgsql/lib:${PATH}
#         export LD_LIBRARY_PATH=/usr/local/pgsql/lib:${LD_LIBRARY_PATH}
#         export PGDATA=/usr/local/pgsql/data
#         export PGUSER=postgres
#         #  postgres (PostgreSQL) 20devel
#         postgres --version
#         # PostgreSQL 20devel
#         pg_config --version
#         pg_config
#         # BINDIR = /usr/local/pgsql/bin
#         # DOCDIR = /usr/local/pgsql/share/doc
#         # HTMLDIR = /usr/local/pgsql/share/doc
#         # INCLUDEDIR = /usr/local/pgsql/include
#         # PKGINCLUDEDIR = /usr/local/pgsql/include
#         # INCLUDEDIR-SERVER = /usr/local/pgsql/include/server
#         # LIBDIR = /usr/local/pgsql/lib
#         # PKGLIBDIR = /usr/local/pgsql/lib
#         # LOCALEDIR = /usr/local/pgsql/share/locale
#         # MANDIR = /usr/local/pgsql/share/man
#         # SHAREDIR = /usr/local/pgsql/share
#         # SYSCONFDIR = /usr/local/pgsql/etc
#         # PGXS = /usr/local/pgsql/lib/pgxs/src/makefiles/pgxs.mk
#         # CONFIGURE =  '--without-icu' '--without-readline' '--without-zlib' '--disable-rpath' '--enable-depend'
#         # CC = gcc
#         # CPPFLAGS = -D_GNU_SOURCE
#         # CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wmissing-format-attribute -Wold-style-declaration -Wimplicit-fallthrough=5 -Wcast-function-type -Wshadow=compatible-local -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -Wstrict-prototypes -Wold-style-definition
#         # CFLAGS_SL = -fPIC
#         # LDFLAGS = -Wl,--as-needed
#         # LDFLAGS_EX = 
#         # LDFLAGS_SL = 
#         # LIBS = -lpgcommon -lpgport -lm 
#         # VERSION = PostgreSQL 20devel
#         initdb
#         pg_ctl -l logfile start
#         psql --version
#         psql -d postgres -c "SELECT version();"
#         psql -d postgres -c "SELECT current_setting('server_version_num');"
#         popd
#         #
#         # sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
#         # sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"
#         # sudo apt-get install r-base-dev acl
#         #
#         sudo apt-get install -qq --no-install-recommends build-essential ca-certificates curl gcc gfortran libblas-dev libbz2-dev libcairo2-dev libcurl4-openssl-dev libicu-dev libjpeg-dev liblapack-dev liblzma-dev libpcre2-dev libpng-dev libreadline-dev libssl-dev libtiff-dev libx11-dev libxml2-dev libxt-dev zlib1g-dev -y
#         #
#         # https://rstudio.github.io/r-manuals/r-admin/Obtaining-R.html
#         sudo apt install subversion -y
#         # r-devel
#         svn checkout https://svn.r-project.org/R/trunk/ r-src
#         pushd r-src
#         ./configure --help
#         ./configure --enable-R-shlib --disable-java --disable-byte-compiled-packages --disable-rpath --without-ICU --without-recommended-packages
#         make -j4
#         sudo make install
#         popd
#         export PATH=/usr/local/bin:$PATH
#         R --version
#
#     - name: Script
#       run: |
#         sudo su - postgres
#         #
#         export PATH=/usr/local/pgsql/bin:$PATH
#         export PATH=/usr/local/pgsql/lib:${PATH}
#         export LD_LIBRARY_PATH=/usr/local/pgsql/lib:${LD_LIBRARY_PATH}
#         export PGDATA=/usr/local/pgsql/data
#         export PGUSER=postgres
#         #
#         USE_PGXS=1 SHLIB_LINK=-lgcov PG_CPPFLAGS="-fprofile-arcs -ftest-coverage -O0" make
#         sudo make install
#         make installcheck || (cat regression.diffs && false)
#
#     - name: After Success
#       # success() returns true, when none of the previous steps have failed or been canceled.
#       if: ${{ success() }}
#       # Uploads code coverage to codecov.io
#       run: bash <(curl -s https://codecov.io/bash)

  job_18_ubuntu-24_04-arm:
    name: PG 18 ubuntu-24.04-arm
    # JUL 18 2026 AUG 17 2026
    # ubuntu-22.04-arm
    # https://docs.github.com/en/actions/reference/runners/github-hosted-runners
    # noble (24.04) arm64 (64-bit ARM)
    # https://wiki.postgresql.org/wiki/Apt
    # https://ftp.postgresql.org/pub/repos/apt/dists/noble-pgdg/main/binary-arm64/Packages.gz
    # arm64 (i.e., M1/M2/M3, graviton etc) CPUs
    # 24.04 (“noble”, amd64 and arm64),
    # https://cloud.r-project.org/
    runs-on: ubuntu-24.04-arm
    env:
      PG: 18
    steps:
      - name: Echo site details
        run: echo PG $PG
 
      - name: Checkout code
        uses: actions/checkout@v6
 
      - name: Before Script
        run: |
          set -x -v -e
          echo "Minimal"
          uname -m
          uname -a
          cat /proc/cpuinfo
          cat /etc/os-release
          set +x +v +e
          echo Building plr with PostgreSQL $PG
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update -qq
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
          sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"
          sudo apt-get install -qq r-base-dev acl
          sudo R --version
          # Seems PG does not come pre-installed
          # sudo /etc/init.d/postgresql stop
          sudo apt-get remove --purge postgresql\*
          sudo rm -rf /etc/postgresql /var/lib/postgresql
          sudo apt-get install postgresql-$PG
          sudo apt-get install postgresql-server-dev-$PG
          echo 'local   all             postgres                                trust' | sudo tee /etc/postgresql/$PG/main/pg_hba.conf > /dev/null
          # Builds under "runner"
          # Github Actions require elevated priviledges
          # sudo setfacl -Rm u:postgres:rwx,d:u:runner:rwx /home/runner
          sudo pg_ctlcluster $PG main reload

      - name: Script
        run: |
          sudo pg_lsclusters
          export USE_PGXS=1
          SHLIB_LINK=-lgcov PG_CPPFLAGS="-fprofile-arcs -ftest-coverage -O0" make
          # USE_PGXS=1 is not required in Travis, and it is required in Github Actions
          sudo USE_PGXS=1 make install
          /usr/lib/postgresql/$PG/bin/pg_config
          make installcheck PGUSER=postgres || (cat regression.diffs && false)

      - name: After Success
        # success() returns true, when none of the previous steps have failed or been canceled.
        if: ${{ success() }}
        # Uploads code coverage to codecov.io
        run: bash <(curl -s https://codecov.io/bash)

  job_build:
    name: PG ${{ matrix.pg }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      PG: ${{ matrix.pg }}
    strategy:
      matrix:
        include:
          # SEEN JUN 2026 AUG 2026
          # Ubuntu 24.04 - ubuntu-latest or ubuntu-24.04
          # https://github.com/actions/runner-images
          # noble (24.04, LTS), plucky (25.04, amd64 only)
          # https://wiki.postgresql.org/wiki/Apt
          # https://apt.postgresql.org/pub/repos/apt/dists/
          # ##
          # https://ftp.postgresql.org/pub/repos/apt/dists/noble-pgdg/
          # Regular expression search - "Package: postgresql-18$"
          # https://ftp.postgresql.org/pub/repos/apt/dists/noble-pgdg/main/binary-amd64/Packages
          - pg: 18
            os: ubuntu-latest
          - pg: 17
            os: ubuntu-latest
          - pg: 16
            os: ubuntu-latest
          - pg: 15
            os: ubuntu-latest
          - pg: 14
            os: ubuntu-latest
          - pg: 13
            os: ubuntu-latest
          - pg: 12
            os: ubuntu-latest
          - pg: 11
            os: ubuntu-latest
          - pg: 10
            os: ubuntu-latest
    steps:
      - name: Echo site details
        run: echo PG $PG
 
      - name: Checkout code
        uses: actions/checkout@v6
 
      - name: Before Script
        run: |
          echo Building plr with PostgreSQL $PG
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update -qq
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
          sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"
          sudo apt-get install -qq r-base-dev acl
          sudo R --version
          sudo /etc/init.d/postgresql stop
          sudo apt-get remove --purge postgresql\*
          sudo rm -rf /etc/postgresql /var/lib/postgresql
          sudo apt-get install postgresql-$PG
          sudo apt-get install postgresql-server-dev-$PG
          echo 'local   all             postgres                                trust' | sudo tee /etc/postgresql/$PG/main/pg_hba.conf > /dev/null
          # Builds under "runner"
          # Github Actions require elevated priviledges
          sudo setfacl -Rm u:postgres:rwx,d:u:runner:rwx /home/runner
          sudo pg_ctlcluster $PG main reload

      - name: Script
        run: |
          sudo pg_lsclusters
          export USE_PGXS=1
          SHLIB_LINK=-lgcov PG_CPPFLAGS="-fprofile-arcs -ftest-coverage -O0" make
          # USE_PGXS=1 is not required in Travis, and it is required in Github Actions
          sudo USE_PGXS=1 make install
          /usr/lib/postgresql/$PG/bin/pg_config
          make installcheck PGUSER=postgres || (cat regression.diffs && false)

      - name: After Success
        # success() returns true, when none of the previous steps have failed or been canceled.
        if: ${{ success() }}
        # Uploads code coverage to codecov.io
        run: bash <(curl -s https://codecov.io/bash)

