name: Callee of Windows Builds PL/R
run-name: Callee of Windows Builds PL/R - ${{ github.event.head_commit.message }}

env:
  TZ: UTC

permissions:
  contents: write

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        required: false
        default: false

  workflow_call:
    inputs:
      debug_enabled:
        type: boolean
        required: false
        default: false
      ragged_schedule:
        type: string
        required: true


jobs:
  build_test_install:
    name: matid ${{ matrix.matid }} R ${{ matrix.rversion }} PGsrc ${{ matrix.pgSRCversion }} PGbin ${{ matrix.pgWINversion }} ${{ matrix.compilerEnv }} ${{ matrix.Platform }}  ${{ matrix.os }} ${{ matrix.Configuration }} PGSRC ${{ matrix.buildpgFromSRC }} PGSRCMETH ${{ matrix.buildpgFromSRCmethod }} SRCCTB ${{ matrix.buildpgANDplrInSRCcontrib }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.GithubActionsIgnoreFail == 'true' && true || false }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(inputs.ragged_schedule) }}

    defaults:
      run:
        shell: ${{ matrix.shellEnv || 'bash' }}

    steps:

      - name: Echo
        run: |
          echo "Nothing"
