
name: Callee of plr Ubuntu jobs
run-name: Callee of plr Ubuntu jobs - ${{ github.event.head_commit.message }}

env:
  TZ: UTC

on:

  workflow_call:
    inputs:
      debug_enabled:
        type: boolean
        required: false
        default: false
      ragged_schedule:
        type: string
        required: true

jobs:

  ubuntu_job_runner:
    name: PG ${{ matrix.pg }} R ${{ matrix.R }} os ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.GithubActionsIgnoreFail == 'true' && true || false }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(inputs.ragged_schedule) }}

    steps:

    - name: Git Checkout this Repository Code
      uses: actions/checkout@v6

    - name: Matrix Variables
      run: |
        set -x -v -e
        export PGfromSource="notset"
        if [ $(echo "${{ matrix.PG }}" | grep -qE "^[0-9][0-9]$" && echo 0) ]
        then
          export PGfromSource="false"
        else
          export PGfromSource="true"
        fi
        echo "PGfromSource=${PGfromSource}" >> ${GITHUB_ENV}
        
        echo "PGfromSource: ${PGfromSource}"

    - name: Get Linux Host Information
      run: |
        bash ./get_linux_host_info.sh

    - name: Guarantee PostgreSQL is Not Installed
      run: |
        bash ./guarantee_postgres_is_not_installed.sh

    - name: Refresh APT
      run: |
        set -x -v -e
        sudo apt-get update -qq

    - name: Acquire PostgreSQL-Dev (and PostgreSQL to test)
      run: |
        set -x -v -e
        # two(2) consecutive digits
        if [ $(echo "${{ matrix.PG }}" | grep -qE "^[0-9][0-9]$" && echo 0) ]
        then
          echo "Postgres from repository binary ..."
          bash ./get_postgres_binaries_compiled_on_ubuntu_from_postgres.org.sh ${{ matrix.PG }}
        else
          echo "Postgres from source ..."
          bash ./get_latest_postgres_source_branch_or_tag.sh ${{ matrix.PG }}
        fi

    - name: Acquire R-Dev (and R to test)
      run: |
        set -x -v -e
        echo "R from CRAN ..."
        bash ./get_debian_r_binaries_on_ubuntu_from_cran.sh

    - name: Install PL/R
      run: |
        set -x -v -e
        # two(2) consecutive digits
        if [ $(echo "${{ matrix.PG }}" | grep -qE "^[0-9][0-9]$" && echo 0) ]
        then
          echo "PL/R from Postgres from repository binary ..."
          bash ./build_install_plr_from_binary_postgres_on_ubuntu.sh
        else
          echo "PG and PL/R from Postgres from source ... DEBUG and CODE COVERAGE"
          bash ./build_install_plr_and_postgres_from_source_on_ubuntu.sh
        fi

    - name: Test (Check) PL/R
      run: |
        set -x -v -e
        # two(2) consecutive digits
        if [ $(echo "${{ matrix.PG }}" | grep -qE "^[0-9][0-9]$" && echo 0) ]
        then
          echo "Test of PL/R from Postgres from repository binary ..."
          bash ./test_plr_from_binary_postgres_on_ubuntu.sh
        else
          # NOT "two(2) consecutive digits" (PG is from Source)
          echo "Test of PL/R from Postgres from source ..."
          bash ./test_plr_from_source_postgres_on_ubuntu.sh
          # PG and PLR build results. Show me everything
          echo "**** ${PG_SOURCE} ****"
          ls -alrt -R "${PG_SOURCE}"
        fi


    # Uploads code coverage to codecov.io
    - name: Gather (any) .gcno with .gcda files, and Then Submit to codecov.io
      # NOT "two(2) consecutive digits"
      if: ${{ env.PGfromSource == 'true' }}
      run: |
        set -x -v -e
        echo "Upload to codecov.io of PL/R from Postgres from source ..."
        # gcc flag "--coverage" produce .gcno and .gcna (required) files here.
        bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }} -s ${{ env.PG_SOURCE }}/build/contrib/plr/plr.so.p     -n bash-plr-C-files-coverage-reports
        # # UNTRIED
        # #
        # # FAILED: [code=1] meson-internal__coverage-xml
        # # (WARNING) Unrecognized GCOV output for /PGSOURCE/src/backend/utils/adt/numeric.c
        # # (ERROR) Exiting because of parse errors.
        # # You can run gcovr with --gcov-ignore-parse-errors
        #
        # # Ninja produced the (PG and PLR) from source C files coverage.xml (gcov or lcov/genhtml)
        # # gcovr required for "coverage-text AND coverage-xml"
        # # https://mesonbuild.com/Feature-autodetection.html
        bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }} -f ${{ env.PG_SOURCE }}/build/meson-logs/coverage.xml -n bash-plr-Ninja-coverage.xml-report

    # .gcno files are generated at compile time 
    # .gcda (gcov data) files are generated at runtime
    - name: Upload the (PG and PLR) from source PLR C files coverage reports to Codecov
      # NOT "two(2) consecutive digits"
      if: ${{ env.PGfromSource == 'true' }}
      uses: codecov/codecov-action@v7
      with:
        verbose: true
        directory: ${{ env.PG_SOURCE }}/build/contrib/plr/plr.so.p
        name: plr-C-files-coverage-reports
        # Tokenless uploading is unsupported. (SEEN SEP 2026)
        # This assumes that you've set your Codecov token inside Settings > Secrets as CODECOV_TOKEN.
        # https://github.com/codecov/codecov-action
        token: ${{ secrets.CODECOV_TOKEN }} 

#   # UNTRIED
    # # UNTRIED
    # #
    # # FAILED: [code=1] meson-internal__coverage-xml
    # # (WARNING) Unrecognized GCOV output for /PGSOURCE/src/backend/utils/adt/numeric.c
    # # (ERROR) Exiting because of parse errors.
    # # You can run gcovr with --gcov-ignore-parse-errors
    #
    # Ninja coverage.xml is expected to be in build/meson-logs/coverage.xml
    - name: Upload the (PG and PLR) from source C files Ninja coverage.xml Report to Codecov
      # NOT "two(2) consecutive digits"
      if: ${{ env.PGfromSource == 'true' }}
      uses: codecov/codecov-action@v7
      with:
        verbose: true
        name: plr-Ninja-coverage.xml-report
        disable_search: true
        # gcovr required for "coverage-text AND coverage-xml"
        # https://mesonbuild.com/Feature-autodetection.html
        files: ${{ env.PG_SOURCE }}/build/meson-logs/coverage.xml
        # Tokenless uploading is unsupported. (SEEN SEP 2026)
        # This assumes that you've set your Codecov token inside Settings > Secrets as CODECOV_TOKEN.
        # https://github.com/codecov/codecov-action
        token: ${{ secrets.CODECOV_TOKEN }} 
