
name: Windows Builds PLR jobs
run-name: Windows Builds PLR jobs - ${{ github.event.head_commit.message }}

env:
  TZ: UTC

on: 
  push:
  pull_request: 
  workflow_dispatch:
      debug_enabled:
        type: boolean
        required: false
        default: false
  schedule:
    - cron: '30 1 * * *'

jobs:

          # Note, the x86 Cygwin Server will "not start" on Github Actions.
          # Therfore cygwin x86 is "not PostgreSQL regression testable."
          #
          # Repository R and Repository Postgresql
          # Package: R
          # https://www.cygwin.com/packages/summary/R.html
          # Package: postgresql
          # https://www.cygwin.com/packages/summary/postgresql.html
          #
          # current Cygwin repository
#         {"matid": "01", "os": "windows-2025-vs2026", "GithubActionsIgnoreFail": "false", "compilerEnv": "cygwin", "Platform": "x64", "Configuration": "Release" }

  windows_scheduled_daily_job_caller:
    name: Windows daily builds
    if: ${{ github.event_name == 'schedule' && github.event.schedule == '30 1 * * *' }}
    uses: ./.github/workflows/buildPLR2.yml
    with:
      ragged_schedule: >
        [
        ]
#         { "matid": "01", "os": "windows-2025-vs2026", "GithubActionsIgnoreFail": "false", "compilerEnv": "cygwin", "Platform": "x64", "Configuration": "Release" }

  windows_fullbuildable_job_caller:
    name: Windows all builds
    if: ${{ github.event_name != 'schedule' }}
    uses: ./.github/workflows/buildPLR2.yml
    with:
      # note: no matid: 13 exists
#         { "matid": "notset", "os": "notset",                "GithubActionsIgnoreFail": "notset", "compilerEnv": "notset",      "shellEnv": "notset",   "compilerExe": "notset", "Platform": "notset", "Configuration": "notset", "rversion": "notset",        "R_HOME": "notset",        "R_ARCH": "notset", "pgSRCversion": "notset", "buildpgFromSRC": "notset", "buildpgFromSRCmethod": "notset", "buildpgANDplrInSRCcontrib": "notset", "PG_HOME": "notset",        "pgWINversion": "notset", "MSYS2testonpgWIN": "notset" } 
      ragged_schedule: >
        [
          { "matid": "01",     "os": "windows-2025-vs2026",   "GithubActionsIgnoreFail": "false",  "compilerEnv": "cygwin",                                                       "Platform": "x64",    "Configuration": "Release"                                    },
          { "matid": "03",     "os": "windows-2025-vs2026",   "GithubActionsIgnoreFail": "false",  "compilerEnv": "UCRT64",     "shellEnv": "msys2 {0}", "compilerExe": "gcc",    "Platform": "x64",    "Configuration": "Debug",  "rversion": "devel-x86_64",  "R_HOME":  "C:\\RINSTALL", "R_ARCH": "/x64",   "pgSRCversion": "master", "buildpgFromSRC": "true",  "buildpgFromSRCmethod": "meson",                                          "PG_HOME": "C:\\PGINSTALL"                                                         },
          { "matid": "14",     "os": "windows-2025-vs2026",   "GithubActionsIgnoreFail": "false",  "compilerEnv": "UCRT64",     "shellEnv": "msys2 {0}", "compilerExe": "gcc",    "Platform": "x64",    "Configuration": "Debug",  "rversion": "devel-x86_64",  "R_HOME":  "C:\\RINSTALL", "R_ARCH": "/x64",   "pgSRCversion": "master",                                                               "buildpgANDplrInSRCcontrib": "true",   "PG_HOME": "C:\\PGINSTALL"                                                         },
          { "matid": "02",     "os": "windows-11-vs2026-arm", "GithubActionsIgnoreFail": "false",  "compilerEnv": "CLANGARM64", "shellEnv": "msys2 {0}", "compilerExe": "clang",  "Platform": "x64",    "Configuration": "Debug",  "rversion": "devel-aarch64", "R_HOME":  "C:\\RINSTALL",                                               "buildpgFromSRC": "false",                                                                           "PG_HOME": "repo"                                                                  },
          { "matid": "04", "os": "windows-2025-vs2026", "GithubActionsIgnoreFail": "false", "compilerEnv": "UCRT64", "shellEnv": "msys2 {0}", "compilerExe": "gcc", "Platform": "x64", "Configuration": "Debug", "rversion": "devel", "R_HOME": "C:\\RINSTALL", "R_ARCH": "/x64", "pgSRCversion": "master", "buildpgFromSRC": "true", "buildpgFromSRCmethod": "meson", "PG_HOME": "C:\\PGINSTALL" },
          { "matid": "05", "os": "windows-2025-vs2026", "GithubActionsIgnoreFail": "false", "compilerEnv": "UCRT64", "shellEnv": "msys2 {0}", "compilerExe": "gcc", "Platform": "x64", "Configuration": "Debug", "rversion": "4.6.1", "R_HOME": "C:\\RINSTALL", "R_ARCH": "/x64", "pgSRCversion": "master", "buildpgFromSRC": "true", "buildpgFromSRCmethod": "meson", "PG_HOME": "C:\\PGINSTALL" },
          { "matid": "06", "os": "windows-2025-vs2026", "GithubActionsIgnoreFail": "false", "compilerEnv": "UCRT64", "shellEnv": "msys2 {0}", "compilerExe": "gcc", "Platform": "x64", "Configuration": "Debug", "rversion": "devel", "R_HOME": "C:\\RINSTALL", "R_ARCH": "/x64", "pgSRCversion": "REL_19_STABLE", "buildpgFromSRC": "true", "buildpgFromSRCmethod": "meson", "PG_HOME": "C:\\PGINSTALL" },
          { "matid": "07", "os": "windows-2025-vs2026", "GithubActionsIgnoreFail": "false", "compilerEnv": "UCRT64", "shellEnv": "msys2 {0}", "compilerExe": "gcc", "Platform": "x64", "Configuration": "Release", "rversion": "4.6.1", "R_HOME": "C:\\RINSTALL", "R_ARCH": "/x64", "pgSRCversion": "REL_19_STABLE", "buildpgFromSRC": "true", "buildpgFromSRCmethod": "meson", "PG_HOME": "C:\\PGINSTALL" },
          { "matid": "08", "os": "windows-2025-vs2026", "GithubActionsIgnoreFail": "false", "compilerEnv": "UCRT64", "shellEnv": "msys2 {0}", "compilerExe": "gcc", "Platform": "x64", "Configuration": "Release", "rversion": "4.6.1", "R_HOME": "C:\\RINSTALL", "R_ARCH": "/x64", "pgSRCversion": "REL_18_STABLE", "buildpgFromSRC": "true", "buildpgFromSRCmethod": "meson", "PG_HOME": "C:\\PGINSTALL", "pgWINversion": "18.6-1", "MSYS2testonpgWIN": "true" },
          { "matid": "09", "os": "windows-2025-vs2026", "GithubActionsIgnoreFail": "false", "compilerEnv": "UCRT64", "shellEnv": "msys2 {0}", "compilerExe": "gcc", "Platform": "x64", "Configuration": "Release", "rversion": "4.6.1", "R_HOME": "C:\\RINSTALL", "R_ARCH": "/x64", "pgSRCversion": "REL_17_STABLE", "buildpgFromSRC": "true", "buildpgFromSRCmethod": "meson", "PG_HOME": "C:\\PGINSTALL", "MSYS2testonpgWIN": "true" },
          { "matid": "10", "os": "windows-2025-vs2026", "GithubActionsIgnoreFail": "false", "compilerEnv": "UCRT64", "shellEnv": "msys2 {0}", "compilerExe": "gcc", "Platform": "x64", "Configuration": "Release", "rversion": "4.6.1", "R_HOME": "C:\\RINSTALL", "R_ARCH": "/x64", "pgSRCversion": "REL_16_STABLE", "buildpgFromSRC": "true", "buildpgFromSRCmethod": "meson", "PG_HOME": "C:\\PGINSTALL", "pgWINversion": "16.15-1", "MSYS2testonpgWIN": "true" },
          { "matid": "11", "os": "windows-2025-vs2026", "GithubActionsIgnoreFail": "false", "compilerEnv": "UCRT64", "shellEnv": "msys2 {0}", "compilerExe": "gcc", "Platform": "x64", "Configuration": "Release", "rversion": "4.6.1", "R_HOME": "C:\\RINSTALL", "R_ARCH": "/x64", "pgSRCversion": "REL_15_STABLE", "buildpgFromSRC": "true", "buildpgFromSRCmethod": "make", "PG_HOME": "C:\\PGINSTALL", "pgWINversion": "15.19-1", "MSYS2testonpgWIN": "true" },
          { "matid": "12", "os": "windows-2025-vs2026", "GithubActionsIgnoreFail": "false", "compilerEnv": "UCRT64", "shellEnv": "msys2 {0}", "compilerExe": "gcc", "Platform": "x64", "Configuration": "Release", "rversion": "4.6.1", "R_HOME": "C:\\RINSTALL", "R_ARCH": "/x64", "pgSRCversion": "REL_14_STABLE", "buildpgFromSRC": "true", "buildpgFromSRCmethod": "make", "PG_HOME": "C:\\PGINSTALL", "pgWINversion": "14.24-1", "MSYS2testonpgWIN": "true" }
        ]
