
name: Windows Builds PLR jobs
run-name: Windows Builds PLR jobs - ${{ github.event.head_commit.message }}

env:
  TZ: UTC

on: 
  push:
  pull_request: 
  workflow_dispatch:
      debug_enabled:
        type: boolean
        required: false
        default: false
  schedule:
    - cron: '30 1 * * *'

jobs:

          # Note, the x86 Cygwin Server will "not start" on Github Actions.
          # Therfore cygwin x86 is "not PostgreSQL regression testable."
          #
          # Repository R and Repository Postgresql
          # Package: R
          # https://www.cygwin.com/packages/summary/R.html
          # Package: postgresql
          # https://www.cygwin.com/packages/summary/postgresql.html
          #
          # current Cygwin repository
#         {"matid": "01", "os": "windows-2025-vs2026", "GithubActionsIgnoreFail": "false", "compilerEnv": "cygwin", "Platform": "x64", "Configuration": "Release" }

  windows_scheduled_daily_job_caller:
    name: Windows daily builds
    if: ${{ github.event_name == 'schedule' && github.event.schedule == '30 1 * * *' }}
    uses: ./.github/workflows/buildPLR2.yml
    with:
      ragged_schedule: >
        [
          { "matid": "01", "os": "windows-2025-vs2026", "GithubActionsIgnoreFail": "false", "compilerEnv": "cygwin", "Platform": "x64", "Configuration": "Release" }
        ]

  windows_fullbuildable_job_caller:
    name: Windows all builds
    if: ${{ github.event_name != 'schedule' }}
    uses: ./.github/workflows/buildPLR2.yml
    with:
      ragged_schedule: >
        [
          { "matid": "01", "os": "windows-2025-vs2026",   "GithubActionsIgnoreFail": "false", "compilerEnv": "cygwin",                                                      "Platform": "x64", "Configuration": "Release" },
          { "matid": "03", "os": "windows-2025-vs2026",   "GithubActionsIgnoreFail": "false", "compilerEnv": "UCRT64",     "shellEnv": "msys2 {0}", "compilerExe": "gcc",   "Platform": "x64", "Configuration": "Debug",  "rversion": "devel-x86_64",  "R_HOME":  "C:\\RINSTALL", "R_ARCH": "/x64", "pgSRCversion": "master", "buildpgFromSRC": "true",  "buildpgFromSRCmethod": "meson", "PG_HOME": "C:\\PGINSTALL" },
          { "matid": "14", "os": "windows-2025-vs2026",   "GithubActionsIgnoreFail": "false", "compilerEnv": "UCRT64",     "shellEnv": "msys2 {0}", "compilerExe": "gcc",   "Platform": "x64", "Configuration": "Debug",  "rversion": "devel-x86_64",  "R_HOME":  "C:\\RINSTALL", "R_ARCH": "/x64", "pgSRCversion": "master", "buildpgANDplrInSRCcontrib": "true",                        "PG_HOME": "C:\\PGINSTALL" },
          { "matid": "02", "os": "windows-11-vs2026-arm", "GithubActionsIgnoreFail": "false", "compilerEnv": "CLANGARM64", "shellEnv": "msys2 {0}", "compilerExe": "clang", "Platform": "x64", "Configuration": "Debug",  "rversion": "devel-aarch64", "R_HOME":  "C:\\RINSTALL",                                             "buildpgFromSRC": "false",                                  "PG_HOME": "repo" }
        ]
