# This is a basic workflow to help you get started with Actions

name: daily plr
run-name: daily plr - ${{ github.event.head_commit.message }}

on: 
   push:
   pull_request: 
   workflow_dispatch:
   schedule:
    # * is a special character in YAML so you have to quote this string
      - cron:  '30 1 * * *'
jobs:
  master:
    # SEEN MAY 2025
    # Ubuntu 24.04	ubuntu-latest
    # https://github.com/actions/runner-images
    # noble (24.04, LTS)
    # https://wiki.postgresql.org/wiki/Apt
    # https://apt.postgresql.org/pub/repos/apt/dists/
    runs-on: ubuntu-latest
    steps:
      - name: Echo site details
        run: echo building master

      - name: Checkout code
        uses: actions/checkout@v5

      - name: checkout postgres
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq r-base-dev acl bison flex libssl-dev
          sudo R --version
          sudo /etc/init.d/postgresql stop
          sudo apt-get remove --purge postgresql\*
          sudo rm -rf /etc/postgresql /var/lib/postgresql
          git clone --depth=1 https://github.com/postgres/postgres.git
          pushd postgres
          ./configure
          make
          sudo make install
          export PATH=/usr/local/pgsql/bin:$PATH
          initdb -D data
          pg_ctl -D data -l logfile start
          popd

      - name: Script
        run: |
          export USE_PGXS=1
          export PATH=/usr/local/pgsql/bin:$PATH
          SHLIB_LINK=-lgcov PG_CPPFLAGS="-fprofile-arcs -ftest-coverage -O0" make
          # USE_PGXS=1 is not required in Travis, and it is required in Github Actions
          sudo USE_PGXS=1 PATH=/usr/local/pgsql/bin:$PATH make install
          psql --version
          make installcheck || (cat regression.diffs && false)
        env:
          USE_PGXS: 1

  REL_18_:
    # SEEN MAY 2025
    # Ubuntu 24.04	ubuntu-latest
    # https://github.com/actions/runner-images
    # noble (24.04, LTS)
    # https://wiki.postgresql.org/wiki/Apt
    # https://apt.postgresql.org/pub/repos/apt/dists/
    runs-on: ubuntu-latest
    steps:
      - name: Echo site details
        run: echo building master

      - name: Checkout code
        uses: actions/checkout@v5

      - name: checkout postgres
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq r-base-dev acl bison flex libssl-dev
          sudo R --version
          sudo /etc/init.d/postgresql stop
          sudo apt-get remove --purge postgresql\*
          sudo rm -rf /etc/postgresql /var/lib/postgresql
          export RET=$(git ls-remote --tags https://github.com/postgres/postgres.git | cut -c 52- | grep -c 'REL_18_[0-9]')
          if [ "${RET}" -gt "0" ]
          then
            export GITTAG=$(git ls-remote --tags https://github.com/postgres/postgres.git | cut -c 52- | grep -e 'REL_18_[0-9]' | tail -n 1)
            echo -n "Release(s) are found.  Taking the last Release . . . GITTAG: ${GITTAG}"
          else
            export RET=$(git ls-remote --tags https://github.com/postgres/postgres.git | cut -c 52- | grep -c 'REL_18_RC[0-9]')
            echo "Release(s) are not found.  Trying Release Candidates."
            if [ "${RET}" -gt "0" ]
            then
              export GITTAG=$(git ls-remote --tags https://github.com/postgres/postgres.git | cut -c 52- | grep -e 'REL_18_RC[0-9]' | tail -n 1)
              echo -n "Release Candidate(s) are found.  Taking the last Release Candidate . . . GITTAG: ${GITTAG}"
            else
              export RET=$(git ls-remote --tags https://github.com/postgres/postgres.git | cut -c 52- | grep -c 'REL_18_BETA[0-9]')
              echo "Release Candidate(s) are not found. Trying Betas."
              if [ "${RET}" -gt "0" ]
              then
                export GITTAG=$(git ls-remote --tags https://github.com/postgres/postgres.git | cut -c 52- | grep -e 'REL_18_BETA[0-9]' | tail -n 1)
                echo -n "Beta(s) are found. Taking the last Beta . . . GITTAG: ${GITTAG}"
              else
                echo "Beta(s) are not found."
              fi
            fi
          fi
          echo "GITTAG: ${GITTAG}"
          git clone --branch $GITTAG --depth=1 https://github.com/postgres/postgres.git
          pushd postgres
          ./configure
          make
          sudo make install
          export PATH=/usr/local/pgsql/bin:$PATH
          initdb -D data
          pg_ctl -D data -l logfile start
          popd

      - name: Script
        run: |
          export USE_PGXS=1
          export PATH=/usr/local/pgsql/bin:$PATH
          SHLIB_LINK=-lgcov PG_CPPFLAGS="-fprofile-arcs -ftest-coverage -O0" make
          # USE_PGXS=1 is not required in Travis, and it is required in Github Actions
          sudo USE_PGXS=1 PATH=/usr/local/pgsql/bin:$PATH make install
          psql --version
          make installcheck || (cat regression.diffs && false)
        env:
          USE_PGXS: 1
