# This is a basic workflow to help you get started with Actions

name: plr daily
run-name: plr daily - ${{ github.event.head_commit.message }}

on: [push, pull_request, workflow_dispatch]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 1 * * *'
jobs:
  master:
    # SEEN JUL 2024
    # Ubuntu 22.04	ubuntu-latest
    # https://github.com/actions/runner-images
    # jammy (22.04, LTS)
    # https://wiki.postgresql.org/wiki/Apt
    # https://apt.postgresql.org/pub/repos/apt/dists/
    runs-on: ubuntu-latest
    steps:
      - name: Echo site details
        run: echo building master

      - name: Checkout code
        uses: actions/checkout@v4

      - name: checkout postgres
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq r-base-dev acl bison flex libssl-dev
          sudo R --version
          sudo /etc/init.d/postgresql stop
          sudo apt-get remove --purge postgresql\*
          sudo rm -rf /etc/postgresql /var/lib/postgresql
          git clone --depth=1 https://github.com/postgres/postgres.git
          pushd postgres
          ./configure
          make
          sudo make install
          export PATH=/usr/local/pgsql/bin:$PATH
          initdb -D data
          pg_ctl -D data -l logfile start
          popd

      - name: Script
        run: |
          export USE_PGXS=1
          export PATH=/usr/local/pgsql/bin:$PATH
          SHLIB_LINK=-lgcov PG_CPPFLAGS="-fprofile-arcs -ftest-coverage -O0" make
          # USE_PGXS=1 is not required in Travis, and it is required in Github Actions
          sudo USE_PGXS=1 PATH=/usr/local/pgsql/bin:$PATH make install
          psql --version
          make installcheck || (cat regression.diffs && false)
        env:
          USE_PGXS: 1
